from django.urls import path
from . import views

urlpatterns = [
    path('process/', views.process_dashboard, name="process"),
    path('dashboard/list/<str:filter_type>/<str:client_type>/',
         views.dashboard_list, name='dashboard_list'),
    path('reports/', views.reports, name="reports"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('all-clients/', views.view_all_clients, name="all-clients"),
    path('view-scheduled/', views.scheduled_financials,
         name="view-scheduled"),
    path('financials-progress/', views.financials_progress,
         name="financials-progress"),
    path('search-users/', views.search_users,
         name="search-users"),
    path('search-vat-clients/', views.search_vat_clients,
         name="search-vat-clients"),
    path('get-clients-for-month-or-accountant/', views.process_vat_clients_for_period,
         name="process_vat_clients_for_period"),

    path('update-financial-year/<int:financial_year_id>/', views.update_client_financial,
         name='update-client-financial'),
    path('create-or-update-vat/', views.create_or_update_vat,
         name="create-or-update-vat"),
    path('client-financial-years/create/', views.create_clients_for_financial_year,
         name='create_client_financial_year'),
    path("client/<int:id>/", views.ClientDetailView.as_view(), name="client-detail"),
    path("ajax/update-vat-status/", views.ajax_update_vat_status,
         name="ajax_update_vat_status"),
    path("ajax/update-comment/", views.ajax_update_comment,
         name="ajax_update_comment"),
    path("overview/",
         views.view_service_overview, name="view-service-overview"),
    path("book-service/",
         views.book_service_dates, name="book-service"),
    path("progress-update-financial-dates/<int:client_id>/",
         views.progress_update_financials, name="progress-update-financials"),
    path("financials-productivity-monitor/",
         views.financials_productivity_monitor, name="financials-productivity-monitor"),
]
