# Generated by Django 5.1.4 on 2025-08-19 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('cell_number', models.CharField(max_length=50, null=True)),
                ('contact_person', models.CharField(max_length=150, null=True)),
                ('contact_person_cell', models.CharField(max_length=50, null=True)),
                ('month_end', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_active', models.BooleanField(default=False)),
                ('is_sa_resident', models.BooleanField(default=True)),
                ('last_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('income_tax_number', models.CharField(max_length=15, null=True, unique=True)),
                ('paye_reg_number', models.CharField(max_length=15, null=True, unique=True)),
                ('uif_reg_number', models.CharField(max_length=25, null=True, unique=True)),
                ('entity_reg_number', models.CharField(max_length=25, null=True, unique=True)),
                ('birthday_of_entity', models.DateField(null=True)),
                ('vat_reg_number', models.CharField(max_length=25, null=True, unique=True)),
                ('registered_address', models.CharField(max_length=150, null=True)),
                ('coida_reg_number', models.CharField(max_length=15, null=True, unique=True)),
                ('internal_id_number', models.CharField(max_length=15, null=True, unique=True)),
                ('uif_dept_reg_number', models.CharField(max_length=15, null=True, unique=True)),
            ],
            options={
                'permissions': [('update_client', 'A User can update client information')],
            },
        ),
        migrations.CreateModel(
            name='ClientCipcReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_date', models.DateField(null=True)),
                ('invoice_date', models.DateField(null=True)),
                ('comment', models.TextField(null=True)),
            ],
            options={
                'permissions': [('change_invoice_date', 'Can edit the invoice date of a CIPC return'), ('change_return_date', 'A User can change the return date on the app')],
            },
        ),
        migrations.CreateModel(
            name='ClientFinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('invoice_date', models.DateField(null=True)),
                ('secretarial_start_date', models.DateField(null=True)),
                ('secretarial_finish_date', models.DateField(null=True)),
                ('itr14_start_date', models.DateField(null=True)),
                ('itr14_date', models.DateField(null=True)),
                ('wp_done', models.BooleanField(default=False)),
                ('afs_done', models.BooleanField(default=False)),
                ('posting_done', models.BooleanField(default=False)),
                ('itr34c_issued', models.BooleanField(default=False)),
                ('client_invoiced', models.BooleanField(default=False)),
                ('comment', models.TextField(null=True)),
                ('tax_comment', models.TextField(null=True)),
                ('sec_comment', models.TextField(null=True)),
                ('inv_comment', models.TextField(null=True)),
            ],
            options={
                'permissions': [('change_invoice_date', 'Can edit the invoice date'), ('change_tax_date', 'A User can change tax dates on financial statements progress'), ('change_acc_date', 'Can change the start and finish date on financial'), ('change_sec_date', 'A User canchange secretarial date')],
            },
        ),
        migrations.CreateModel(
            name='ClientProvisionalTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_date', models.DateField(null=True)),
                ('invoice_date', models.DateField(null=True)),
                ('prov_tax_numb', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('comment', models.TextField(null=True)),
            ],
            options={
                'permissions': [('change_invoice_date', 'Can edit the invoice date'), ('change_irp_date', 'A User can change the IRP6 start and finish dates')],
            },
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('comment', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Client Services',
                'permissions': [('change_client_service', 'A user can change a client service offering')],
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYearSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Financial years setup',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Months',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_category', models.CharField(max_length=10, unique=True)),
                ('category_descr', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vat categories',
            },
        ),
        migrations.CreateModel(
            name='VatSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('client_notified', models.BooleanField(default=False)),
                ('comment', models.TextField(null=True)),
                ('date_marked_submitted', models.DateTimeField(null=True)),
                ('date_invoiced', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Vat Submission History',
                'permissions': [('change_vat201_status', 'A user can change the VAT201 submission status'), ('change_emp_201_invoice_date', 'A User can change the invoice dates for VAT201')],
            },
        ),
    ]
