# Generated by Django 5.1.4 on 2025-01-29 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='VatCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_category', models.CharField(max_length=10, unique=True)),
                ('category_descr', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150, null=True)),
                ('month_end', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('last_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('income_tax_number', models.CharField(max_length=15, null=True)),
                ('paye_reg_number', models.CharField(max_length=15, null=True)),
                ('uif_reg_number', models.CharField(max_length=15, null=True)),
                ('cipc_reg_number', models.CharField(max_length=15, null=True)),
                ('vat_reg_number', models.CharField(max_length=15, null=True)),
                ('registered_address', models.CharField(max_length=150, null=True)),
                ('coida_reg_number', models.CharField(max_length=15, null=True)),
                ('internal_id_number', models.CharField(max_length=15, null=True)),
                ('uif_dept_reg_number', models.CharField(max_length=15, null=True)),
                ('accountant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('client_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='client.clienttype')),
            ],
        ),
        migrations.CreateModel(
            name='ClientFinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.financialyear')),
            ],
            options={
                'unique_together': {('client', 'financial_year')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='financial_years',
            field=models.ManyToManyField(related_name='clients', through='client.ClientFinancialYear', to='client.financialyear'),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='client.vatcategories'),
        ),
    ]
