# Generated by Django 5.1.4 on 2026-04-06 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='accountant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientcipcreturnhistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='clientcipcreturnhistory',
            name='invoiced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cipc_marked_invoiced', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientcipcreturnhistory',
            name='marked_finished_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cipc_marked_finished', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientfinancialyear',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='clientprovisionaltax',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='clientprovisionaltax',
            name='invoiced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prov_tax_marked_invoiced', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprovisionaltax',
            name='marked_finished_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prov_tax_marked_finished', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_services', to='client.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='client.clienttype'),
        ),
        migrations.AddField(
            model_name='event',
            name='client_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_service_events', to='client.clientservice'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_events', to='client.event'),
        ),
        migrations.AddField(
            model_name='clientprovisionaltax',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.financialyear'),
        ),
        migrations.AddField(
            model_name='clientfinancialyear',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.financialyear'),
        ),
        migrations.AddField(
            model_name='clientcipcreturnhistory',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.financialyear'),
        ),
        migrations.AddField(
            model_name='client',
            name='financial_years',
            field=models.ManyToManyField(related_name='clients', through='client.ClientFinancialYear', to='client.financialyear'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_fin_year', to='client.financialyear'),
        ),
        migrations.AddField(
            model_name='financialyearsetup',
            name='client_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.clienttype'),
        ),
        migrations.AddField(
            model_name='financialyearsetup',
            name='financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.financialyear'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_month_for_coida_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coida_clients', to='client.month'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_month_for_paye_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paye_clients', to='client.month'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_month_for_vat_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_clients', to='client.month'),
        ),
        migrations.AddField(
            model_name='projectoccurence',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectoccurence',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_recurring_events', to='client.event'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_project_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_project_stages', to='client.event'),
        ),
        migrations.AddField(
            model_name='projectstagecompletion',
            name='project_occurence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_occurence_completion', to='client.projectoccurence'),
        ),
        migrations.AddField(
            model_name='projectstagecompletion',
            name='project_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stage_completion', to='client.projectstage'),
        ),
        migrations.AddField(
            model_name='recurringevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_events', to='client.event'),
        ),
        migrations.AddField(
            model_name='recurringevent',
            name='recurring_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_recurring_events', to='client.recurringtype'),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_service', to='client.service'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_service',
            field=models.ManyToManyField(related_name='client_services', through='client.ClientService', to='client.service'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_stages', to='client.stage'),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='client.vatcategory'),
        ),
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_client', to='client.client'),
        ),
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='marked_notified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_notified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='marked_paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='marked_submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.month'),
        ),
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.financialyear'),
        ),
        migrations.AlterUniqueTogether(
            name='clientprovisionaltax',
            unique_together={('client', 'financial_year', 'prov_tax_numb')},
        ),
        migrations.AlterUniqueTogether(
            name='clientfinancialyear',
            unique_together={('client', 'financial_year')},
        ),
        migrations.AlterUniqueTogether(
            name='clientcipcreturnhistory',
            unique_together={('client', 'financial_year')},
        ),
        migrations.AlterUniqueTogether(
            name='financialyearsetup',
            unique_together={('financial_year', 'client_type')},
        ),
        migrations.AlterUniqueTogether(
            name='projectoccurence',
            unique_together={('event', 'original_date')},
        ),
        migrations.AlterUniqueTogether(
            name='projectstagecompletion',
            unique_together={('project_occurence', 'project_stage')},
        ),
        migrations.AlterUniqueTogether(
            name='clientservice',
            unique_together={('client', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='projectstage',
            unique_together={('stage', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='vatsubmissionhistory',
            unique_together={('client', 'year', 'month')},
        ),
    ]
