# Generated by Django 5.1.4 on 2026-02-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'permissions': [('update_client', 'A User can update client information')]},
        ),
        migrations.AlterModelOptions(
            name='clientfinancialyear',
            options={'permissions': [('change_invoice_date', 'Can edit the invoice date'), ('change_tax_date', 'A User can change tax dates on financial statements progress'), ('change_acc_date', 'Can change the start and finish date on financial'), ('change_sec_date', 'A User can change secretarial date')]},
        ),
        migrations.AddField(
            model_name='clientfinancialyear',
            name='inv_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
