# Generated by Django 5.1.4 on 2025-02-17 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_clientfinancialyear_finish_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='first_month_for_coida_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coida_clients', to='client.months'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_month_for_paye_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paye_clients', to='client.months'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_month_for_vat_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_clients', to='client.months'),
        ),
    ]
