# Generated by Django 5.1.4 on 2025-08-18 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcipcreturnhistory',
            name='invoiced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cipc_marked_invoiced', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientcipcreturnhistory',
            name='marked_finished_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cipc_marked_finished', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientprovisionaltax',
            name='invoiced_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prov_tax_marked_invoiced', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientprovisionaltax',
            name='marked_finished_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prov_tax_marked_finished', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vatsubmissionhistory',
            name='marked_notified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_notified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vatsubmissionhistory',
            name='marked_paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vatsubmissionhistory',
            name='marked_submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
