# Generated by Django 5.1.4 on 2025-07-17 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='date_marked_submitted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='marked_notified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_notified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='marked_paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='marked_submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
