# Generated by Django 5.1.4 on 2025-02-19 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_months_client_first_month_for_coida_sub_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='months',
            options={'verbose_name_plural': 'Months'},
        ),
        migrations.AlterModelOptions(
            name='vatcategories',
            options={'verbose_name_plural': 'Vat categories'},
        ),
        migrations.AddField(
            model_name='client',
            name='first_financial_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_fin_year', to='client.financialyear'),
        ),
        migrations.AlterField(
            model_name='client',
            name='internal_id_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
