# Generated by Django 5.1.4 on 2026-05-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientgroup_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfinancialyear',
            name='inv_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
