# Generated by Django 5.1.4 on 2025-02-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_months_options_alter_vatcategories_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.months')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.financialyear')),
            ],
            options={
                'unique_together': {('client', 'year', 'month')},
            },
        ),
    ]
