# Generated by Django 5.1.4 on 2025-02-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_vatsubmissionhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vatsubmissionhistory',
            options={'verbose_name_plural': 'Vat Submission History'},
        ),
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='client_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vatsubmissionhistory',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vatsubmissionhistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='vatsubmissionhistory',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.months'),
        ),
        migrations.AlterField(
            model_name='vatsubmissionhistory',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.financialyear'),
        ),
    ]
