# Generated by Django 5.1.4 on 2026-05-03 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'permissions': [
                ('update_client', 'A User can update client information')]},
        ),
        migrations.AlterModelOptions(
            name='clientfinancialyear',
            options={'ordering': ('client', 'financial_year'), 'permissions': [('change_invoice_date', 'Can edit the invoice date'), ('change_tax_date', 'A User can change tax dates on financial statements progress'), (
                'change_acc_date', 'Can change the start and finish date on financial'), ('change_sec_date', 'A User can change secretarial date')]},
        ),
        # migrations.AddField(
        #     model_name='clientfinancialyear',
        #     name='inv_number',
        #     field=models.CharField(blank=True, max_length=20, null=True),
        # ),
        migrations.AddField(
            model_name='client',
            name='client_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='group_clients', to='client.clientgroup'),
        ),
    ]
